### ISSUE TITLE
process_fragment_file.py IndexError

### ISSUE THREAD

**Issue by gigglypear** [spcdot/CopyscAT#1]
Hello!

I was using process_fragment_file.py to create a fragment matrix of my own data, and I encountered the following error after the file has processed 20900000 lines:

Traceback (most recent call last):
  File "process_fragment_file.py", line 94, in <module>
    cell_ids[line_split[3]][line_split[0]][setIndex] += readLength
IndexError: index 249 is out of bounds for axis 0 with size 249

The command I have used was following, which I believe was not of any error:

`python3 process_fragment_file.py -i ~/CopyscAT_analysis/H7/fragments.tsv.gz -o ~/CopyscAT_analysis/H7/fragments.tsv -b 1000000 -f 10000 -g ~/CopyscAT_analysis/H7/hg38_chrom_sizes.tsv`

Is there anything I could do to solve it?

**Comment by spcdot** [comment]
Can you double check the assembly version your data file was aligned with? If it is hg19 aligned and your chrom-sizes file is in hg38 then it could be trying to write to a chromosome bin that isn't there. Alternately, check for the presence of non-standard chromosomes in your alignment (Copy-scATs chrom.sizes file only looks at chr1-22,chrX,chrY and chrM).

**Comment by gigglypear** [comment]
Thank you for your reply! It appear to be the genome version issue - the data was hg19 aligned. Changing genome file into hg19 resolved the issue. Thank you so much!
