### ISSUE TITLE
Error with process_fragment_file.py

### ISSUE THREAD

**Issue by chent5** [spcdot/CopyscAT#11]
Thanks a lot for developing this package.

I ran into an error when using process_fragment_file.py to process my own fragment file. The last few lines of the log file look like this:

"Reading line 831400000
Reading line 831500000
Reading line 831600000
Reading line 831700000
Reading line 831800000

Traceback (most recent call last):
  File "~/process_fragment_file.py", line 96, in <module>
    cell_ids[line_split[3]][line_split[0]][setIndex] += readLength
KeyError: 'KI270728.1"

I am not sure where this error comes from... Could you help me to solve this issue? Thank you so much!

**Comment by chent5** [comment]
I have successfully solved this issue. Sorry for the interruption.

**Comment by mvinyard** [comment]
> I have successfully solved this issue. Sorry for the interruption.

@chent5, do you mind sharing what you did? I presumed this came from a mis-match in chromosomes in the `.tsv` input vs. chromsomes in the `chrom_sizes` file - but curious what you did to patch this the error I received flagged the same chromosome as that which is not found. Thanks! 

```
Traceback (most recent call last):
  File "/home/mvinyard/notebooks/CA/CopyscAT/CopyscAT/process_fragment_file.py", line 96, in <module>
    cell_ids[line_split[3]][line_split[0]][setIndex] += readLength
KeyError: 'KI270728.1'
```

**Comment by chent5** [comment]
Use below Unix command line to generate a new fragment.gz file (named "atac_fragments_chr.tsv.gz") only containing "chr" information:

`zcat dir_to_fragment_file/atac_fragments.tsv.gz | grep "chr" > atac_fragments_chr.tsv
gzip atac_fragments_chr.tsv`

**Comment by mvinyard** [comment]
> Use below Unix command line to generate a new fragment.gz file (named "atac_fragments_chr.tsv.gz") only containing "chr" information:
> 
> `zcat dir_to_fragment_file/atac_fragments.tsv.gz | grep "chr" > atac_fragments_chr.tsv gzip atac_fragments_chr.tsv`

Thanks!

**Comment by KeWXiong** [comment]
> > Use below Unix command line to generate a new fragment.gz file (named "atac_fragments_chr.tsv.gz") only containing "chr" information:
> > `zcat dir_to_fragment_file/atac_fragments.tsv.gz | grep "chr" > atac_fragments_chr.tsv gzip atac_fragments_chr.tsv`
> 
> Thanks!

Could you help me with the preparation of reference file in the python script? What does the genome file mean, and where can I download? Thanks!
