### ISSUE TITLE
error in normalizeMatrixN

### ISSUE THREAD

**Issue by Dragonlongzhilin** [spcdot/CopyscAT#18]
Nice tool! I used the following code to infer CNV for my scATAC-seq data.
zcat fragments.tsv.gz | grep "chr" | gzip > fragments_chr.tsv.gz
process_fragment_file.py -i fragments_chr.tsv.gz -o single.assay.tsv -b 1000000 -f 10000 -g hg38_chrom_sizes.tsv

single.assay <- readInputTable("single.assay.tsv")
single.assay.k.norm <- normalizeMatrixN(single.assay, logNorm = FALSE, maxZero=2000,imputeZeros = FALSE,blacklistProp = 0.8,blacklistCutoff=125,dividingFactor=1,upperFilterQuantile = 0.95) 

error:
[1] "23403 cells passing filter"
Error in `mutate_at()`:
! `match` must be a character vector of non empty strings.
Run `rlang::last_error()` to see where the error occurred.

**Comment by AritaZ-hang** [comment]
Hello there, after 7 months I've encountered the same problem. So I wonder have you solved it yet?

**Comment by NoemieL** [comment]
Hi. You should run the "initialiseEnvironment" step beforehand and it works properly. It was mentioned in issue #5 .

**Comment by spcdot** [comment]
Be sure to run initializeEnvironment first, and make sure your cell suffix matches your input barcodes. The other thing to check is your cell barcode format - Copy-scAT is written to expect some sort of suffix (like CellRanger ATAC puts down) such as -1, -2, etc. If you don't have a suffix to your cell barcodes, I suggest adding one manually and then running Copy-scAT. It uses the suffix to select the cell barcodes in multiple functions so some non-zero suffix is required.
