### ISSUE TITLE
Error in collapseChrom3N

### ISSUE THREAD

**Issue by mrichter23** [spcdot/CopyscAT#20]
Hi!
I'm trying to run CopyscAT. I've built the references for hg19 and I've run process_fragment_file.py on the fragment file. Then I load the resulting data with
 > scData <- readInputTable("~/BM_fragments_100kb_20000_copyscat_hg19.tsv")
Then I run 
> scData_k_norm <- normalizeMatrixN(scData,logNorm = FALSE,maxZero=10000,imputeZeros = FALSE,blacklistProp = 0.8,blacklistCutoff=125,dividingFactor=1,upperFilterQuantile = 0.95)
However, when I try to run collapseChrom3N, I get the following error:

Error in `mutate()`:
! Problem while computing `chromArm = scCNVCaller$cytoband_data$V4`.
✖ `chromArm` must be size 30971 or 1, not 3114.

Any idea on how what I could do to not cause the error?

**Comment by spcdot** [comment]
Hi,

Looks like your references were generated using a 1e6 window size (hence the 3114 for the cytoband data) and your matrix was  generated using 100kb bins. I would suggest using 1e6 bins for the python step, in my experience scATAC data is sparse enough that if you go down below 500kb, you tend to get a lot of zeros and the output won't be as useful. Alternately you can re-run generateReferences using a 100kb window size, but I would not recommend this, as in my experience that's too small to be optimal.

Cheers,

Ana

**Comment by mrichter23** [comment]
Ahh ok, thank you!
