### ISSUE TITLE
process_fragment_file.py fails to process fragments.tsv.gz from cell ranger-atac(arc) 2.0.0

### ISSUE THREAD

**Issue by camiel-m** [spcdot/CopyscAT#7]
Hi there,

I'm trying to run your package on tumor data processed with the new version of cell ranger-atac.
It crashes with the following error:

```
Traceback (most recent call last):
  File "process_fragment_file.py", line 90, in <module>
    readLength=int(line_split[2])-int(line_split[1])-1
IndexError: list index out of range
```

Most likely this is because in the [new version of cellranger there is a header in the tsv file](https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/release-notes#header) that process_fragment_file.py does not yet account for. Maybe checking for # as the first character in the line would fix the issue?

**Comment by spcdot** [comment]
Thanks for the heads up - I just put in a quick patch which should fix that issue.

Ana

**Comment by camiel-m** [comment]
Thanks Ana, it works for me now
